# Generated by Django 5.0.4 on 2024-04-07 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_specialization_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='specialist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bot.specialist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(default='specialists/specialist_default.png', upload_to='specialists'),
        ),
    ]
