# Generated by Django 5.0.4 on 2024-04-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_contacts_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='on_site_link',
            field=models.TextField(default='1'),
        ),
    ]
