# Generated by Django 5.0.4 on 2024-04-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_location_on_site_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='link_on_site',
            field=models.URLField(default=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='on_site_link',
            field=models.TextField(),
        ),
    ]
