# Generated by Django 5.0.4 on 2024-04-07 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_specialist_link_on_site_alter_location_on_site_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='sessionrecord',
            options={'verbose_name': 'Запись на занятие', 'verbose_name_plural': 'Записи на занятия'},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'Саециалист', 'verbose_name_plural': 'Саециалисты'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='location',
            name='on_map_link',
            field=models.TextField(verbose_name='Ссылка на карту'),
        ),
        migrations.AlterField(
            model_name='location',
            name='on_site_link',
            field=models.TextField(verbose_name='Ссылка на сайт'),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='session',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bot.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='session',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bot.specialist', verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sessionrecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to='bot.session', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='sessionrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to='bot.user', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='first_name',
            field=models.CharField(max_length=300, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='last_name',
            field=models.CharField(max_length=300, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='link_on_site',
            field=models.URLField(verbose_name='Ссылка на сайте'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(default='specialists/specialist_default.png', upload_to='specialists', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='bot.specialization', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
