# Generated by Django 5.0.4 on 2024-04-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_contacts_options_alter_direction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecord',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
